In [13]:
import pandas as pd
import ast

In [14]:
ranked_candidates = pd.read_csv(
    r"D:\AI_ATS_Resume_Screening_System\resume\test\csv\candidate_ranking.csv"
)

ranked_candidates.head()

,resume_name,resume_text,text_length,length_category,completeness_score,clean_text,skills_found,skill_count,similarity_score,match_percentage,skill_score,final_score,ATS_Rank
0,Niteesh Java Developer.pdf,Niteesh Kusumba\nniteeshkusumba.java@gmail.com...,21020,Long,3,niteesh kusumba sr java full stack developer c...,"['python', 'sql', 'excel', 'r', 'mysql', 'gith...",6,0.146991,100.000000,40,22.289359,1
1,Bapuji Hadoop developer.pdf,Bapuji\nSr. Hadoop Developer\nPhone: +1(224)-7...,14384,Long,4,bapuji sr hadoop developer phone email profess...,"['python', 'sql', 'excel', 'tableau', 'r', 'my...",9,0.088774,95.176116,50,21.214146,2
2,Sai Srinivas_Sr_Java_Developer.pdf,Sai Srinivas\nSr. Java/J2EE Developer\nCell: (...,21215,Long,3,sai srinivas sr javajee developer cell email s...,"['python', 'sql', 'excel', 'r', 'mysql', 'gith...",8,0.108027,87.763342,40,19.561886,3
3,Venkata_SrPHP_Developer.pdf,Venkata\nSr. PHP / Drupal Developer\nEmail: ve...,9953,Long,3,venkata sr php drupal developer email cell sum...,"['python', 'sql', 'excel', 'r', 'sas', 'mysql']",6,0.145222,85.985031,30,19.165512,4
4,Mani_Hadoop.pdf,Mani\nSr. Hadoop Developer\nEmail: vmaniv08@gm...,13562,Long,3,mani sr hadoop developer email contact profess...,"['python', 'sql', 'excel', 'tableau', 'r', 'my...",8,0.093595,83.230969,40,18.551650,5

In [15]:
job_skills = {

    "python",
    "sql",
    "machine learning",
    "pandas",
    "numpy",
    "statistics",
    "data analysis",
    "power bi"

}

In [16]:
def convert_to_list(skill_string):

    try:
        return ast.literal_eval(skill_string)

    except:
        return []

ranked_candidates["skills_found"] = (
    ranked_candidates["skills_found"]
    .apply(convert_to_list)
)

In [17]:
def analyze_skill_gap(candidate_skills):

    candidate_skills = set(candidate_skills)

    matched_skills = (
        job_skills.intersection(candidate_skills)
    )

    missing_skills = (
        job_skills.difference(candidate_skills)
    )

    return (
        list(matched_skills),
        list(missing_skills)
    )

In [18]:
results = ranked_candidates["skills_found"].apply(
    analyze_skill_gap
)

ranked_candidates["matched_skills"] = (
    results.apply(lambda x: x[0])
)

ranked_candidates["missing_skills"] = (
    results.apply(lambda x: x[1])
)

In [19]:
ranked_candidates["missing_skill_count"] = (
    ranked_candidates["missing_skills"]
    .apply(len)
)

In [20]:
ranked_candidates[
    [
        "resume_name",
        "match_percentage",
        "matched_skills",
        "missing_skills"
    ]
].head()

,resume_name,match_percentage,matched_skills,missing_skills
0,Niteesh Java Developer.pdf,100.000000,"[python, sql]","[statistics, power bi, data analysis, machine ..."
1,Bapuji Hadoop developer.pdf,95.176116,"[python, sql]","[statistics, power bi, data analysis, machine ..."
2,Sai Srinivas_Sr_Java_Developer.pdf,87.763342,"[python, sql]","[statistics, power bi, data analysis, machine ..."
3,Venkata_SrPHP_Developer.pdf,85.985031,"[python, sql]","[statistics, power bi, data analysis, machine ..."
4,Mani_Hadoop.pdf,83.230969,"[python, sql]","[statistics, power bi, data analysis, machine ..."

In [21]:
def generate_recommendation(missing_skills):

    if len(missing_skills) == 0:

        return (
            "Excellent match for this role."
        )

    return (
        "Recommended to learn: "
        + ", ".join(missing_skills)
    )

In [22]:
ranked_candidates["recommendation"] = (
    ranked_candidates["missing_skills"]
    .apply(generate_recommendation)
)

In [23]:
top_candidate = ranked_candidates.iloc[0]

print("Candidate:")
print(top_candidate["resume_name"])

print("\nMatch Percentage:")
print(top_candidate["match_percentage"])

print("\nMatched Skills:")
print(top_candidate["matched_skills"])

print("\nMissing Skills:")
print(top_candidate["missing_skills"])

print("\nRecommendation:")
print(top_candidate["recommendation"])

Candidate:
Niteesh Java Developer.pdf

Match Percentage:
100.0

Matched Skills:
['python', 'sql']

Missing Skills:
['statistics', 'power bi', 'data analysis', 'machine learning', 'pandas', 'numpy']

Recommendation:
Recommended to learn: statistics, power bi, data analysis, machine learning, pandas, numpy

In [24]:
ranked_candidates.to_csv(
    r"D:\AI_ATS_Resume_Screening_System\resume\test\csv\final_ats_results.csv",
    index=False
)

print("Final ATS results saved!")

Final ATS results saved!